### ISSUE TITLE
App fails to build locally

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/demo-kendo#2]
Chrome console shows
```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:9000/dist/app-build.js
	Error loading http://localhost:9000/dist/app-build.js
	Error loading http://localhost:9000/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.js
    at o (http://localhost:9000/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:13219)
```

I built it the standard way:

#### Step 1 - cloned the repo
```
C:\work\aurelia-ui-toolkits
λ git clone https://github.com/aurelia-ui-toolkits/demo-kendo.git
Cloning into 'demo-kendo'...
remote: Counting objects: 133, done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 133 (delta 27), reused 131 (delta 27), pack-reused 0
Receiving objects: 100% (133/133), 488.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (27/27), done.
Checking connectivity... done.
```
#### Step 2 run the installs
```
npm install
jspm install
```

#### Step 3 run the app
```
λ gulp watch
[18:37:52] Using gulpfile C:\work\aurelia-ui-toolkits\demo-kendo\gulpfile.js
[18:37:52] Starting 'build'...
[18:37:52] Starting 'clean'...
[18:37:52] Finished 'clean' after 9.91 ms
[18:37:52] Starting 'build-system'...
[18:37:52] Starting 'build-html'...
[18:37:52] Starting 'build-css'...
[18:37:52] Finished 'build-css' after 25 ms
[18:37:53] Finished 'build-html' after 854 ms
[18:37:53] Finished 'build-system' after 923 ms
[18:37:53] Finished 'build' after 937 ms
[18:37:53] Starting 'serve'...
[BS] Local URL: http://localhost:9000
[BS] Serving files from: .
[18:37:54] Finished 'serve' after 1.09 s
[18:37:54] Starting 'watch'...
[18:37:54] Finished 'watch' after 67 ms
```

Perhaps it's too late in the day - but I have no clue what is the problem here. Since the app runs deployed, it ought to be that you did not "check-in" something?

**Comment by JeroenVinke** [comment]
Ah,  I know why this is happening. When you `gulp bundle`,  JSPM modifies the `config.js` file with a reference to the bundled `app-build.js` file. Because I did not `gulp unbundle`,  it is basically still in the bundled state. Will change the gulp tasks to fix this problem, and I will also add some documentation to the readme
