### ISSUE TITLE
Error: (SystemJS) [BABEL] unknown: Unknown option: direct.0

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/demo-kendo#7]
Running `gulp watch` results with

```
Error: (SystemJS) [BABEL] unknown: Unknown option: direct.0
	ReferenceError: [BABEL] unknown: Unknown option: direct.0
	    at Logger.error (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:8955:11)
	    at OptionManager.mergeOptions (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:9463:29)
	    at OptionManager.init (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:9553:10)
	    at File.initOptions (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:8193:75)
	    at new File (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:8183:22)
	    at Pipeline.transform (http://localhost:9000/jspm_packages/npm/babel-core@5.8.38/browser.js:13515:16)
	    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:31:7722)
	    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13014)
	    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:13817)
	    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:14518)
	    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:30:15848)
	    at r._drainQueue (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:3148)
	    at r._drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:3209)
	    at drainQueues (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.4.0/bluebird.min.js:29:1238)
```

@JeroenVinke:  Googling for this message does not yield anything meaningful. Did you change the babel-core version recently? Why does this not happen to you?

**Comment by JeroenVinke** [comment]
nope, we can't update babel-core since newer versions can only be run with JSPM 0.17. I cannot reproduce, did a `git pull`, `npm install` and `jspm install` then `gulp watch` and did not get that error :(

**Comment by adriatic** [comment]
I checked the difference between the definition of the `babel-core` in **[`current package.json`](https://github.com/aurelia-ui-toolkits/demo-kendo/blob/master/package.json#L87)** (being `"babel": "npm:babel-core@^5.6.4"`) and my old copy on my machine which requires `     "babel": "npm:babel-core@^5.8.24"`

To my surprise both versions actually load the same version `babel-core@5.8.38` - so I will try to run the old version and see whether that one works.

**Comment by Thanood** [comment]
I guess we shouldn't pull packages from `@master`. 😃 
In the case of `code-prettify` removing "loader" from the (only) import in the bridge app should remove the error.

**Comment by JeroenVinke** [comment]
Yeah, unfortunately code-prettify does not have versions, but I believe JSPM supports commit hashes as well so that should work

**Comment by adriatic** [comment]
@Thanood writes

> I guess we shouldn't pull packages from `@master`

So, now, I am guessing that this comment references the line below

```
http://localhost:9000/jspm_packages/github/google/code-prettify@master/loader/run_prettify.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

meaning that sometime ago Google changed this url. @JeroenVinke writes about **[`commit hashes`](https://gist.github.com/masak/2415865)** which I believe is a poor man's replacemement for version numbers.

My question is simple: what is the URL that I should be using?

**Comment by NajiJzr** [comment]
Hey guys, I'm having this error after updating my node version from v0.12.18 to v6.9.1. Any news about how to fix this ??

**Comment by JeroenVinke** [comment]
@najiJzr if you can reproduce this in a project that you can share we can have a look

**Comment by adriatic** [comment]
@JeroenVinke you are likely aware of GitHub's strengthening the version support - this is a typical example:

![image](https://user-images.githubusercontent.com/2712405/36858146-61e10932-1d48-11e8-9e59-334371ca4e90.png)
which appears at several places in KendUI catalog app. While such detection seemingly uses the package-lock.json file to detect these issue, I would prefer to deal with this the proper way instead of just deleting package-lock.json files everywhere 👎.

As a person with sympathy for your workload, I am offering to do such cleanup - let me know if that is OK to do.

**Comment by JeroenVinke** [comment]
Of course :smile:
